name: Discord Update

on:
  push:
    paths:
      - "RoadMap.md"

jobs:
  discord:
    runs-on: ubuntu-latest

    steps:
      - name: Send message to Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content":"📢 **New Version changes!**\n\n[View RoadMap](https://github.com/S4PPHIRED/Infernal_Soul/blob/main/RoadMap.md)"}' \
          "${{ secrets.DISCORD_ROADMAP_UPDATE }}"
