name: Discord Update

on:
  push:
    paths:
      - "RoadMap.md"

jobs:
  discord:
    runs-on: ubuntu-latest

    steps:
      - name: Enviar mensaje a Discord
        run: |
          curl -H "Content-Type: application/json" \
          -d '{"content":"📢 New edition in GitHub!"}' \
          "${{ secrets.DISCORD_ROAPMAP_UPDATE }}"
